// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 emailcheck() ", "[example]")
{
	int ret;
	string email;

	email = "ABCDEF@company.com";
	ret = emailcheck(email);
	cout << "test email string is " << email << "\tYour return value is: " << ret << endl;

	INFO("The result should  1\n");
	REQUIRE(ret == 1);
	cout << "--------------------------------------------------\n";

	email = "ABC@company.com";
	ret = emailcheck(email);
	cout << "test email string is " << email << "\tYour return value is: " << ret << endl;

	INFO("The result should  0\n");
	REQUIRE(ret == 0);
	cout << "--------------------------------------------------\n";

	email = "johnsmith@company.io.edu";
	ret = emailcheck(email);
	cout << "test email string is " << email << "\tYour return value is: " << ret << endl;

	INFO("The result should  1\n");
	REQUIRE(ret == 1);
	cout << "--------------------------------------------------\n";
}

TEST_CASE("Ex2 emailcheck() ", "[example]")
{
	int ret;
	string email;

	email = "john@company.server.io";
	ret = emailcheck(email);
	cout << "test email string is " << email << "\tYour return value is: " << ret << endl;

	INFO("The result should  0\n");
	REQUIRE(ret == 0);
	cout << "--------------------------------------------------\n";

	email = "john@company.server";
	ret = emailcheck(email);
	cout << "test email string is " << email << "\tYour return value is: " << ret << endl;

	INFO("The result should  0\n");
	REQUIRE(ret == 0);
	cout << "--------------------------------------------------\n";
}